### ISSUE TITLE
[edge-http]: Server returns `Connection(IncompleteHeaders)` when reader is at EOF.

### ISSUE THREAD

**Issue by AnthonyGrondin** [ivmarkov/edge-net#20]
## Description
Following the implementation of https://rustdoc.etonomy.org/embedded_io_async/trait.Read.html, `Ok(0)` is returned when the reader is at EOF. This happens when using a client such as curl, that closes the connection right after the request; When we read the headers byte by byte, we return right as we hit `\r\n\r\n`. If the connection is closed, the next call to `read()` will return `Ok(0)`. If the connection isn't closed, the next call on `read()` will hang until there is more data to be read or until we hit the timeout.

I discovered this issue using `edge-http` alongside `esp-mbedtls`. In this case, it's because `Ok(0)` is returned when a client sends a [close_notify](https://www.rfc-editor.org/rfc/rfc5246#section-7.2.1) alert.
## Steps to reproduce:

1. Flash a board with [examples/edge_server.rs](https://github.com/esp-rs/esp-mbedtls/blob/main/examples/edge_server.rs). Make sure that logging for level info is enabled for `edge-http`.
2. Once connected, make a request to the board IP using a client that closes the connection such as curl.
   (`curl -k https://<IP>/`)
3. edge-http should show the following error:
  `Handler task 0: Error when handling request: Connection(IncompleteHeaders)`
4. Make a request with a client that doesn't close the connection, such as Firefox.
5. edge-http should keep the connection open, and once the timeout expires, should show the following log:
  `Handler task 1: Connection closed due to timeout`.

## Additional information

Here is the network stream when the client (curl) closes the connection after the request:
![image](https://github.com/user-attachments/assets/a2af6ef2-51e7-4778-a337-14354c6986a3)

Here is the network stream when the client (Firefox) keeps the connection open after the request:
![image](https://github.com/user-attachments/assets/d0ea8d76-85f0-4735-b066-e22b5741bb44)

**Comment by ivmarkov** [comment]
@AnthonyGrondin Thanks for the explanations! Unfortunately, I'm not really sure I understand the problem. Are you saying, that there is some wrong treatment of of the `Read` API by the HTTP server, and if so, where exactly?

Speaking of `Read`, I'm concerned with [this line](https://github.com/esp-rs/esp-mbedtls/blob/main/esp-mbedtls/src/lib.rs#L1009) in your `Read` trait implementation of `esp-mbedtls`. I don't think it implements the `Read` API correctly, because if the TLS reader is at EOF, you are supposed to return `Ok(0)` and not an error.

Could that be the culprit of the issue?

**Comment by ivmarkov** [comment]
By the way and also important: if - [on this line](https://github.com/esp-rs/esp-mbedtls/blob/main/esp-mbedtls/src/lib.rs#L1016) - your TLS code can return 0 - yet - re-trying the read **in the future** would return non-0, then you need to `continue` the loop instead of returning `Ok(usize = 0)` because returning `Ok(0)` really means "I'm at EOF, and this will **not** change for this connection - ever - and I'll continue returning `Ok(0)` for this connection forever, if you continue to call me".

**Comment by AnthonyGrondin** [comment]
So I've had this issue first with `esp-mbedtls`, but I've isolated it to the behaviour of the client, and how it interacts with `esp-wifi` and `edge-http`. I was able to reproduce this by spawning an http server with `esp-wifi` and then making a request with curl.

The issue happens here:
https://github.com/ivmarkov/edge-net/blob/640a4f263986d6d26e2508cdb2f43c8ee5a7bd66/edge-http/src/io.rs#L1006

The first time a client makes a request, it goes to `read_reply_buf()` which calls `read_headers()`. Once the request is completed, `read_reply_buf()` is called again and `read_headers()` is expected to read a new connection. **IF** on the previous request, the connection has been closed, `esp-wifi` will reply with `Ok(0)` when the line above is called, and `read_headers()` will immediately return `Err(Error::IncompleteHeaders)`.

**Comment by ivmarkov** [comment]
> So I've had this issue first with `esp-mbedtls`, but I've isolated it to the behaviour of the client, and how it interacts with `esp-wifi` and `edge-http`. I was able to reproduce this by spawning an http server with `esp-wifi` and then making a request with curl.
> 
> The issue happens here:
> 
> https://github.com/ivmarkov/edge-net/blob/640a4f263986d6d26e2508cdb2f43c8ee5a7bd66/edge-http/src/io.rs#L1006
> 
> The first time a client makes a request, it goes to `read_reply_buf()` which calls `read_headers()`. Once the request is completed, `read_reply_buf()` is called again and `read_headers()` is expected to read a new connection. **IF** on the previous request, the connection has been closed, `esp-wifi` will reply with `Ok(0)` when the line above is called, and `read_headers()` will immediately return `Err(Error::IncompleteHeaders)`.

Just to make sure I understand: looking at `edge-net` `master`, are you sure it breaks really on line 1006, and not on line [1009 instead](https://github.com/ivmarkov/edge-net/blob/master/edge-http/src/io.rs#L1009)?

With that said - I still believe your `Read` trait implementation could be wrong as you are simply not supposed to return an error on end-of-stream. You are supposed to return `Ok(0)` instead simply because this is what the `Read` trait API mandates, and this is what upstream code (like `edge-http` or any other code utilizing a `Read` trait) expects. But this might be an orthogonal issue to the one we are discussing.

As for what happens on line 1009 (if you could confirm you indeed hit line 1009 and not 1006) - yes - this behavior might be a bug so let me dig into it.

**Comment by AnthonyGrondin** [comment]
> Just to make sure I understand: looking at edge-net master, are you sure it breaks really on line 1006, and not on line [1009 instead](https://github.com/ivmarkov/edge-net/blob/master/edge-http/src/io.rs#L1009)?

The issue is indeed at line 1009. I've found that line 1006 is "where the bug starts".

> With that said - I still believe your Read trait implementation could be wrong as you are simply not supposed to return an error on end-of-stream. You are supposed to return Ok(0) instead simply because this is what the Read trait API mandates, and this is what upstream code (like edge-http or any other code utilizing a Read trait) expects. But this might be an orthogonal issue to the one we are discussing.

I agree that the `Read` trait implementation in `esp-mbedtls` needs to be re-worked and that it doesn't follow the specification. I was initially planning on opening an issue in `esp-mbedtls` but while writting it, I found out that it's not specific to `esp-mbedtls`.

> "I'm at EOF, and this will not change for this connection - ever - and I'll continue returning Ok(0) for this connection forever, if you continue to call me".

This is what happens when the connection is closed with `esp-mbedtls`, it returns `Ok(0)`. But this also happens when using `esp-wifi` only. When a reader returns `Ok(0)` after a connection is closed (right after the `\r\n\r\n` bytes), which would be on the next time line 1006 is called, `edge-net` considers this as an `Err(Error::IncompleteHeaders)` rather than a closed connection.

**Comment by ivmarkov** [comment]
> The issue is indeed at line 1009. I've found that line 1006 is "where the bug starts".
> 
> This is what happens when the connection is closed with `esp-mbedtls`, it returns `Ok(0)`. But this also happens when using `esp-wifi` only. When a reader returns `Ok(0)` after a connection is closed (right after the `\r\n\r\n` bytes), which would be on the next time line 1006 is called, `edge-net` considers this as an `Err(Error::IncompleteHeaders)` rather than a closed connection.

I **do** agree it happens exactly as you described!
However - _putting aside the _misleading_ `Err(Error::IncompleteHeaders)` error message just for a moment_, the rest of the code seems to work correctly. What I mean is, if you call `RequestHeaders::receive` or `ResponseHeaders::receive` (which are the only two ways to enter `read_reply_buf`) and you find out the connection is closed, there is nothing else you can do but unroll the stack by indicating to the user that this connection is useless now, as it is closed. No headers (or anything else as a matter of fact) can be expected from it.

For me, the only question is how to indicate "connection is closed" (currently this is indicated with the misleading `Err(Error::IncompleteHeaders)` which is misleading, as the HTTP server logs it as an error, while - as you say - _this is completely normal_).

The simplest approach without changing the API in a significant way would be to just return a different - new - type of error, which indicates "connection closed" rather than "incomplete headers". This is what I [just did](https://github.com/ivmarkov/edge-net/commit/e846ff7be32e6376f814723ebf9d97534140bdfb) as a quick fix. If you could try it out and let me know how it behaves for you?

It is another question if such "connection closed" scenarios should be indicated with an `Error` and rather - whether we should return some sort of an `Ok` result from it instead. But that would mean more obtrusive changes to the call chain - and - somehow these changes would be HTTP **server** specific, because closing the connection by the peer when we try to read _response_ headers (the HTTP **client** case) should remain an error, as that's not an expected and "Ok" behavior.

**Comment by ivmarkov** [comment]
> > With that said - I still believe your Read trait implementation could be wrong as you are simply not supposed to return an error on end-of-stream. You are supposed to return Ok(0) instead simply because this is what the Read trait API mandates, and this is what upstream code (like edge-http or any other code utilizing a Read trait) expects. But this might be an orthogonal issue to the one we are discussing.
> 
> I agree that the `Read` trait implementation in `esp-mbedtls` needs to be re-worked and that it doesn't follow the specification. I was initially planning on opening an issue in `esp-mbedtls` but while writting it, I found out that it's not specific to `esp-mbedtls`.
> 

Now that we (hopefully) addressed and fixed the misleading error message in `http-server`, let me follow up here.
I'm not sure what you mean that the `Read` trait implementation error is not specific to `esp-mbedtls`. It _is_ specific to `esp-mbedtls` in that the bug is in there [on this line](https://github.com/esp-rs/esp-mbedtls/blob/main/esp-mbedtls/src/lib.rs#L1009)?

In relation to `edge-http` specifically, this bug will not result in a panic of the server or anything like that, but WILL result in the server logging a hard error (with `log::error`) because you _do_ return a hard error for EOF rather than `Ok(0)`.
But that would be the only consequence. Still anoying and you should probably fix though.

I'm also wondering why it doesn't happen already and why you are not observing this behavior with `edge-http`?

**Comment by ivmarkov** [comment]
> In relation to `edge-http` specifically, this bug will not result in a panic of the server or anything like that, but WILL result in the server logging a hard error (with `log::error`) because you _do_ return a hard error for EOF rather than `Ok(0)`. But that would be the only consequence. Still anoying and you should probably fix though.
> 
> I'm also wondering why it doesn't happen already and why you are not observing this behavior with `edge-http`?

On a second thought, if it just so happens, that your `Read` trait impl returns this "EOF-as-an-error" at the end of the body stream rather than at the time when `edge-http` tries to read the next request-response from the connection, this might have some pretty dire consequences for the HTTP **client**, as in the `edge-http` client abandoning the connection with a hard error rather than giving the user the opportunity to process the server response body. Especially with complex HTTP body encodings like the chunked one. So I think you definitely need to address that bug.

**Comment by AnthonyGrondin** [comment]
I've made a MRE to showcase the issue using only `esp-wifi`:
https://github.com/AnthonyGrondin/edge-net-bug-mre

I can confirm that https://github.com/ivmarkov/edge-net/commit/e846ff7be32e6376f814723ebf9d97534140bdfb fixes the described issue.

I will try to find time to fix the `Read` implementation of `esp-mbedtls` next week.

**Comment by ivmarkov** [comment]
> I've made a MRE to showcase the issue using only `esp-wifi`: https://github.com/AnthonyGrondin/edge-net-bug-mre

Thanks!

> I can confirm that [e846ff7](https://github.com/ivmarkov/edge-net/commit/e846ff7be32e6376f814723ebf9d97534140bdfb) fixes the described issue.

In that case I'll close this issue, even if I don't have a completely warm, fuzzy feeling for the fact that we propagate `ConnectionClosed` as an error all the way up the call stack chain. But not sure propagating it as some sort of `Ok` response is worth the effort.
