### ISSUE TITLE
Cant build ws_client example

### ISSUE THREAD

**Issue by omani** [ivmarkov/edge-net#29]
```
$ cargo build --release --target riscv32imc-unknown-none-elf --example ws_client
error: target `ws_client` in package `edge-net` requires the features: `std`
Consider enabling them by passing, e.g., `--features="std"`
```

I thought this repo is `no_std`? can someone provide me with a full example of how to run the ws_client example on an esp32c3 with target `riscv32imc-unknown-none-elf`?

**Comment by ivmarkov** [comment]
The library itself might be `no_std`, but the examples are not. Typically, `no_std` networking code still uses STD examples, because otherwise the example needs to be MCU- and HAL- specific.

For the non-ESP-IDF esp32 specifically, your best bet is to first successfully build an example like [this one](https://github.com/esp-rs/esp-hal/blob/v0.20.1/examples/src/bin/wifi_embassy_dhcp.rs), and then replace the plain-TCP-socket parts in it with bits and pieces from the `ws_client` STD example.
