### ISSUE TITLE
mDNS responded examples require std

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [ivmarkov/edge-net#52]
I am interested in using a no_std mDNS responder in embassy.

The README states `Async + no_std + no-alloc implementation of an mDNS responder.`, but the examples provided do require `std`, specified as a required feature in the workspace `Cargo.toml` and it seems the `embedded-io` dependency actually requires `std`.

I'll try extracting the code into a separate example project and see if I can get it working without `std`, but given the "Banner line" talking about it being a `no_std` implementation, I thought it would be good that the examples don't require `std`.

thanks

**Comment by andrewdavidmackenzie** [comment]
It's possible my IDE pulled in some other dependencies when I copy and pasted the code it, and I was getting errors from embedded-io. Anyway...

I was thinking there could still be a no_std example for the host (not an MCU), using heapless and co. no?

**Comment by ivmarkov** [comment]
> It's possible my IDE pulled in some other dependencies when I copy and pasted the code it, and I was getting errors from embedded-io. Anyway...
> 
> I was thinking there could still be a no_std example for the host (not an MCU), using heapless and co. no?

You can do it for the host by using the `tun`/`tap` stuff in `smoltcp` / `embassy-net` and then using `edge-nal-embassy` instead of `edge-nal-std` but I'm not sure how much more "educational" that example would be, because you'll just replace one `edge-net` `Stack` impl (`edge-nal-std`) with another `Stack` impl (`edge-nal-embassy`). 

What is the point?

Putting aside the concrete `Stack` instantiation, the rest of the example doesn't actually care what is your concrete `Stack`, as it only or mostly uses it via the `edge-nal` traits.

**Comment by ivmarkov** [comment]
Closing, as this is not coming soon. If a PR is opened based on `embassy-net` tun/tap or the Esp MCU line, I can merge, as I can support these two setups. Supporting other MCUs would be difficult for me.
